server {
    listen 80;
    server_name _;

    allow ${AVI_SE_DATA_CIDR};
    deny all;

    location / {
        proxy_pass http://127.0.0.1:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Avi-Service-Engine-IP $remote_addr;
        proxy_set_header X-Backend-Node $hostname;
        proxy_set_header X-Backend-Server-IP $server_addr;

        proxy_set_header X-Remote-User $http_x_remote_user;
        proxy_set_header X-Avi-Client-Cert-Auth $http_x_avi_client_cert_auth;
        proxy_set_header X-Avi-Client-Cert-Subject $http_x_avi_client_cert_subject;
        proxy_set_header X-Avi-Client-Cert-Issuer $http_x_avi_client_cert_issuer;
        proxy_set_header X-Avi-Client-Cert-CN $http_x_avi_client_cert_cn;
        proxy_set_header X-Avi-Client-Cert-EDIPI $http_x_avi_client_cert_edipi;
    }
}