apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: app-npl-hostrule
  namespace: default
spec:
  virtualhost:
    fqdn: app-npl.us-east.demo.lab
    enableVirtualHost: true
    applicationProfile: System-Secure-HTTP
    wafPolicy: WAF-Enforcement-Policy
    tls:
      sslProfile: System-Standard-PFS
      sslKeyCertificate:
        name: us-east-wildcard
        type: ref
      termination: edge
    analyticsProfile: System-Analytics-Profile
    analyticsPolicy:
      fullClientLogs:
        enabled: true
        throttle: DISABLED
      logAllHeaders: true
